-- CREAMOS WAREHOUSE 
CREATE WAREHOUSE IF NOT EXISTS PROYECTDE;
-- BAJAMOS DE LOS 10 MINS a 1 MIN
ALTER WAREHOUSE PROYECTDE
    SET AUTO_SUSPEND = 60;

-- CREAMOS LAS BASES DE DATOS PARA CADA CAPA 
-- Y PARA DESAROLLO,PRE-PRODUCCION,PRODUCCION
CREATE DATABASE IF NOT EXISTS DEV_BRONZE_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS DEV_SILVER_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS DEV_GOLD_BD_MODELOS;


CREATE DATABASE IF NOT EXISTS  PRE_BRONZE_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRE_SILVER_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRE_GOLD_BD_MODELOS;

CREATE DATABASE IF NOT EXISTS  PRO_BRONZE_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRO_SILVER_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRO_GOLD_BD_MODELOS;



-- CREAMOS LOS SCHEMAS RAW

CREATE SCHEMA IF NOT EXISTS DEV_BRONZE_BD_MODELOS.RAW;
CREATE SCHEMA IF NOT EXISTS PRE_BRONZE_BD_MODELOS.RAW;
CREATE SCHEMA IF NOT EXISTS PRO_BRONZE_BD_MODELOS.RAW;



-- USAR LA BASE DE DATOS;
USE DATABASE DEV_BRONZE_BD_MODELOS;
USE DATABASE DEV_SILVER_BD_MODELOS;
USE DATABASE DEV_GOLD_BD_MODELOS;

USE DATABASE  PRE_BRONZE_BD_MODELOS;
USE DATABASE  PRE_SILVER_BD_MODELOS;
USE DATABASE  PRE_GOLD_BD_MODELOS;

USE DATABASE  PRO_BRONZE_BD_MODELOS;
USE DATABASE  PRO_SILVER_BD_MODELOS;
USE DATABASE  PRO_GOLD_BD_MODELOS;


