-- CREAMOS WAREHOUSE Y BASE DE DATOS
CREATE WAREHOUSE IF NOT EXISTS PROYECTDE;
-- BAJAMOS DE LOS 10 MINS a 1 MIN
ALTER WAREHOUSE PROYECTDE
    SET AUTO_SUSPEND = 60;
CREATE DATABASE IF NOT EXISTS MODELOS;


-- CREAMOS SCHEMAS
USE DATABASE MODELOS;
CREATE SCHEMA raw;
CREATE SCHEMA bronze;
CREATE SCHEMA silver;
CREATE SCHEMA gold;
CREATE SCHEMA snapshots;


