-- CREAMOS WAREHOUSE 
CREATE WAREHOUSE IF NOT EXISTS PROYECTDE;
-- BAJAMOS DE LOS 10 MINS a 1 MIN
ALTER WAREHOUSE PROYECTDE
    SET AUTO_SUSPEND = 60;

-- CREAMOS LAS BASES DE DATOS PARA CADA CAPA 
-- Y PARA DESAROLLO,PRE-PRODUCCION,PRODUCCION
CREATE DATABASE IF NOT EXISTS DEV_BRONZE_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS DEV_SILVER_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS DEV_GOLD_BD_MODELOS;


CREATE DATABASE IF NOT EXISTS  PRE_BRONZE_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRE_SILVER_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRE_GOLD_BD_MODELOS;

CREATE DATABASE IF NOT EXISTS  PRO_BRONZE_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRO_SILVER_BD_MODELOS;
CREATE DATABASE IF NOT EXISTS  PRO_GOLD_BD_MODELOS;



-- CREAMOS LOS SCHEMAS RAW
USE DEV_BRONZE_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS DEV_BRONZE_BD_MODELOS.RAW;
USE PRE_BRONZE_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRE_BRONZE_BD_MODELOS.RAW;
USE PRO_BRONZE_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRO_BRONZE_BD_MODELOS.RAW;

-- CREAMOS LOS SCHEMAS SNAPSHOT (SCD2)
USE DEV_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS DEV_SILVER_BD_MODELOS.SNAPSHOT;
USE PRE_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRE_SILVER_BD_MODELOS.SNAPSHOT;
USE PRO_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRO_SILVER_BD_MODELOS.SNAPSHOT;

-- CREAMOS LOS SCHEMAS STAGING (modelos intermedios)
USE DEV_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS DEV_SILVER_BD_MODELOS.STAGING;
USE PRE_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRE_SILVER_BD_MODELOS.STAGING;
USE PRO_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRO_SILVER_BD_MODELOS.STAGING;

-- CREAMOS LOS SCHEMAS SILVER (modelos finales)
USE DEV_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS DEV_SILVER_BD_MODELOS.SILVER;
USE PRE_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRE_SILVER_BD_MODELOS.SILVER;
USE PRO_SILVER_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRO_SILVER_BD_MODELOS.SILVER;

-- CREAMOS LOS SCHEMAS GOLD CORE (dimensions + facts)
USE DEV_GOLD_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS DEV_GOLD_BD_MODELOS.GOLD_CORE;
USE PRE_GOLD_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRE_GOLD_BD_MODELOS.GOLD_CORE;
USE PRO_GOLD_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRO_GOLD_BD_MODELOS.GOLD_CORE;

-- CREAMOS LOS SCHEMAS GOLD MART (marts analíticos)
USE DEV_GOLD_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS DEV_GOLD_BD_MODELOS.GOLD_MART;
USE PRE_GOLD_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRE_GOLD_BD_MODELOS.GOLD_MART;
USE PRO_GOLD_BD_MODELOS;
CREATE SCHEMA IF NOT EXISTS PRO_GOLD_BD_MODELOS.GOLD_MART;

-- USAR LA BASE DE DATOS;

USE DATABASE DEV_BRONZE_BD_MODELOS;
USE DATABASE DEV_SILVER_BD_MODELOS;
USE DATABASE DEV_GOLD_BD_MODELOS;

USE DATABASE  PRE_BRONZE_BD_MODELOS;
USE DATABASE  PRE_SILVER_BD_MODELOS;
USE DATABASE  PRE_GOLD_BD_MODELOS;

USE DATABASE  PRO_BRONZE_BD_MODELOS;
USE DATABASE  PRO_SILVER_BD_MODELOS;
USE DATABASE  PRO_GOLD_BD_MODELOS;


