-- CREAMOS ROLE PARA INGESTAR (DLT)
CREATE ROLE IF NOT EXISTS DEV_ROLE_INGEST;

CREATE ROLE IF NOT EXISTS PRE_ROLE_INGEST;
CREATE ROLE IF NOT EXISTS PRO_ROLE_INGEST;


GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE DEV_ROLE_INGEST;

GRANT USAGE
  ON DATABASE DEV_BRONZE_BD_MODELOS
  TO ROLE DEV_ROLE_INGEST;

GRANT CREATE SCHEMA ON DATABASE DEV_BRONZE_BD_MODELOS TO ROLE DEV_ROLE_INGEST;

GRANT ALL ON FUTURE SCHEMAS IN DATABASE DEV_BRONZE_BD_MODELOS TO DEV_ROLE_INGEST;

GRANT USAGE, CREATE TABLE, CREATE VIEW, MODIFY
ON SCHEMA DEV_BRONZE_BD_MODELOS.RAW
TO ROLE DEV_ROLE_INGEST;

-- CREAMOS ROLE PARA INGESTAR (DBT)
CREATE ROLE IF NOT EXISTS DEV_ROLE_TRANSFORM;
CREATE ROLE IF NOT EXISTS PRE_ROLE_TRANSFORM;
CREATE ROLE IF NOT EXISTS PRO_ROLE_TRANSFORM;









GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRE_ROLE_INGEST;

GRANT USAGE
  ON DATABASE PRE_BRONZE_BD_MODELOS
  TO ROLE PRE_ROLE_INGEST;







GRANT CREATE SCHEMA ON DATABASE DEV_BRONZE_BD_MODELOS TO ROLE PRE_ROLE_INGEST;

GRANT ALL ON FUTURE SCHEMAS IN DATABASE DEV_BRONZE_BD_MODELOS TO PRE_ROLE_INGEST;

GRANT USAGE, CREATE TABLE, CREATE VIEW, MODIFY
ON SCHEMA DEV_BRONZE_BD_MODELOS.RAW
TO ROLE PRE_ROLE_INGEST;










  GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRO_ROLE_INGEST;

GRANT USAGE
  ON DATABASE PRO_BRONZE_BD_MODELOS
  TO ROLE PRO_ROLE_INGEST;


GRANT CREATE SCHEMA ON DATABASE DEV_BRONZE_BD_MODELOS TO ROLE PRO_ROLE_INGEST;

GRANT ALL ON FUTURE SCHEMAS IN DATABASE DEV_BRONZE_BD_MODELOS TO PRO_ROLE_INGEST;

GRANT USAGE, CREATE TABLE, CREATE VIEW, MODIFY
ON SCHEMA DEV_BRONZE_BD_MODELOS.RAW
TO ROLE PRO_ROLE_INGEST;











GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE DEV_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE DEV_BRONZE_BD_MODELOS
  TO ROLE DEV_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE DEV_SILVER_BD_MODELOS
  TO ROLE DEV_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE DEV_GOLD_BD_MODELOS
  TO ROLE DEV_ROLE_TRANSFORM;


GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRE_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE PRE_BRONZE_BD_MODELOS
  TO ROLE PRE_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE PRE_SILVER_BD_MODELOS
  TO ROLE PRE_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE PRE_GOLD_BD_MODELOS
  TO ROLE PRE_ROLE_TRANSFORM;


GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRO_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE PRO_BRONZE_BD_MODELOS
  TO ROLE PRO_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE PRO_SILVER_BD_MODELOS
  TO ROLE PRO_ROLE_TRANSFORM;

GRANT USAGE
  ON DATABASE PRO_GOLD_BD_MODELOS
  TO ROLE PRO_ROLE_TRANSFORM;







CREATE USER IF NOT EXISTS USR_DLT_PDE
  PASSWORD = SECRET{{'DLT'}}
  DEFAULT_ROLE = DEV_ROLE_INGEST
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = DEV_BRONZE_BD_MODELOS  --MODELOS.RAW
  MUST_CHANGE_PASSWORD = FALSE;


CREATE USER IF NOT EXISTS USR_DLT_PRE_PDE
  PASSWORD = SECRET{{'DLT_PRE'}}
  DEFAULT_ROLE = PRE_ROLE_INGEST
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = PRE_BRONZE_BD_MODELOS 
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_DLT_PRO_PDE
  PASSWORD = SECRET{{'DLT_PRO'}}
  DEFAULT_ROLE = PRO_ROLE_INGEST
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = PRO_BRONZE_BD_MODELOS  
  MUST_CHANGE_PASSWORD = FALSE;

SHOW GRANTS TO USER USR_DLT_PDE;
GRANT ROLE PRE_ROLE_INGEST
  TO USER USR_DLT_PRE_PDE;
SHOW GRANTS TO USER USR_DLT_PDE;

GRANT ROLE PRO_ROLE_INGEST
  TO USER USR_DLT_PRO_PDE;



CREATE USER IF NOT EXISTS USR_DBT_PDE
  PASSWORD = SECRET{{'DBT'}}
  DEFAULT_ROLE = DEV_ROLE_TRANSFORM
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = DEV_SILVER_BD_MODELOS --MODELOS.BRONZE
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_DBT_PRE_PDE
  PASSWORD = SECRET{{'DBT_PRE'}}
  DEFAULT_ROLE = DEV_ROLE_TRANSFORM
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = DEV_SILVER_BD_MODELOS --MODELOS.BRONZE
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_DBT_PRO_PDE
  PASSWORD = SECRET{{'DBT_PRO'}}
  DEFAULT_ROLE = PRO_ROLE_TRANSFORM
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = PRO_SILVER_BD_MODELOS --MODELOS.BRONZE
  MUST_CHANGE_PASSWORD = FALSE;



GRANT ROLE DEV_ROLE_INGEST
  TO USER USR_DLT_PDE;

GRANT ROLE DEV_ROLE_TRANSFORM
  TO USER USR_DBT_PDE;


GRANT ROLE PRE_ROLE_TRANSFORM
  TO USER USR_DBT_PRE_PDE;


GRANT ROLE PRO_ROLE_TRANSFORM
  TO USER USR_DBT_PRO_PDE;