-- CREAMOS ROLES PARA INGESTAR CON DLT
CREATE ROLE IF NOT EXISTS DEV_ROLE_INGEST;

CREATE ROLE IF NOT EXISTS PRE_ROLE_INGEST;
CREATE ROLE IF NOT EXISTS PRO_ROLE_INGEST;


-- ROLES PARA TRANSFORMAR CON DBT
CREATE ROLE IF NOT EXISTS DEV_ROLE_TRANSFORM;
CREATE ROLE IF NOT EXISTS PRE_ROLE_TRANSFORM;
CREATE ROLE IF NOT EXISTS PRO_ROLE_TRANSFORM;





-- PERMISOS AL ROLE PARA ELL WAREHOUSE 
GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE DEV_ROLE_INGEST;   --INGEST DEV

GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRE_ROLE_INGEST;   --INGEST PRE

  GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRO_ROLE_INGEST;  --INGEST PRO

GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE DEV_ROLE_TRANSFORM; --TRANSFORM DEV 

GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRE_ROLE_TRANSFORM;  --TRANSFORM PRE

GRANT USAGE
  ON WAREHOUSE PROYECTDE
  TO ROLE PRO_ROLE_TRANSFORM;  --TRANSFORM PRO 



-- PERMISOS AL ROLE PARA LA BASE DE DATOS 
GRANT USAGE
  ON DATABASE DEV_BRONZE_BD_MODELOS    
  TO ROLE DEV_ROLE_INGEST;             --INGEST DEV

GRANT USAGE
  ON DATABASE PRE_BRONZE_BD_MODELOS
  TO ROLE PRE_ROLE_INGEST;             --INGEST PRE

GRANT USAGE
  ON DATABASE PRO_BRONZE_BD_MODELOS
  TO ROLE PRO_ROLE_INGEST;            --INGEST PRO





GRANT USAGE
  ON DATABASE DEV_BRONZE_BD_MODELOS
  TO ROLE DEV_ROLE_TRANSFORM;     --TRANSFORM DEV 

GRANT USAGE
  ON DATABASE DEV_SILVER_BD_MODELOS
  TO ROLE DEV_ROLE_TRANSFORM;     --TRANSFORM DEV 

GRANT USAGE
  ON DATABASE DEV_GOLD_BD_MODELOS
  TO ROLE DEV_ROLE_TRANSFORM;    --TRANSFORM DEV 




GRANT USAGE
  ON DATABASE PRE_BRONZE_BD_MODELOS
  TO ROLE PRE_ROLE_TRANSFORM;       --TRANSFORM PRE 

GRANT USAGE
  ON DATABASE PRE_SILVER_BD_MODELOS
  TO ROLE PRE_ROLE_TRANSFORM;        --TRANSFORM PRE 

GRANT USAGE
  ON DATABASE PRE_GOLD_BD_MODELOS
  TO ROLE PRE_ROLE_TRANSFORM;        --TRANSFORM PRE 




GRANT USAGE
  ON DATABASE PRO_BRONZE_BD_MODELOS
  TO ROLE PRO_ROLE_TRANSFORM;        --TRANSFORM PRO 

GRANT USAGE
  ON DATABASE PRO_SILVER_BD_MODELOS
  TO ROLE PRO_ROLE_TRANSFORM;        --TRANSFORM PRO 

GRANT USAGE
  ON DATABASE PRO_GOLD_BD_MODELOS
  TO ROLE PRO_ROLE_TRANSFORM;        --TRANSFORM PRO 






-- PERMISOS AL ROLE PARA LOS SCHEMAS RAW DE LAS BASES DE DATOS BRONZE 

GRANT ALL ON SCHEMA PRE_BRONZE_BD_MODELOS.RAW TO ROLE DEV_ROLE_INGEST;  --INGEST DEV
 

GRANT ALL ON SCHEMA PRE_BRONZE_BD_MODELOS.RAW TO ROLE PRE_ROLE_INGEST;  --INGEST PRE


GRANT ALL ON SCHEMA PRO_BRONZE_BD_MODELOS.RAW TO ROLE PRO_ROLE_INGEST;  --INGEST PRO




-- CREAMOS USUARIOS PARA DLT 
CREATE USER IF NOT EXISTS USR_DLT_PDE
  PASSWORD = SECRET{{'DLT'}}
  DEFAULT_ROLE = DEV_ROLE_INGEST
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = DEV_BRONZE_BD_MODELOS  
  MUST_CHANGE_PASSWORD = FALSE;


CREATE USER IF NOT EXISTS USR_DLT_PRE_PDE
  PASSWORD = SECRET{{'DLT_PRE'}}
  DEFAULT_ROLE = PRE_ROLE_INGEST
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = PRE_BRONZE_BD_MODELOS 
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_DLT_PRO_PDE
  PASSWORD = SECRET{{'DLT_PRO'}}
  DEFAULT_ROLE = PRO_ROLE_INGEST
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = PRO_BRONZE_BD_MODELOS  
  MUST_CHANGE_PASSWORD = FALSE;

-- CREAMOS USUARIOS PARA DBT 
CREATE USER IF NOT EXISTS USR_DBT_PDE
  PASSWORD = SECRET{{'DBT'}}
  DEFAULT_ROLE = DEV_ROLE_TRANSFORM
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = DEV_SILVER_BD_MODELOS 
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_DBT_PRE_PDE
  PASSWORD = SECRET{{'DBT_PRE'}}
  DEFAULT_ROLE = DEV_ROLE_TRANSFORM
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = DEV_SILVER_BD_MODELOS 
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS USR_DBT_PRO_PDE
  PASSWORD = SECRET{{'DBT_PRO'}}
  DEFAULT_ROLE = PRO_ROLE_TRANSFORM
  DEFAULT_WAREHOUSE = PROYECTDE
  DEFAULT_NAMESPACE = PRO_SILVER_BD_MODELOS 
  MUST_CHANGE_PASSWORD = FALSE;




GRANT ROLE DEV_ROLE_INGEST TO USER USR_DLT_PDE;  --INGEST DEV -->  USR_DLT_PDE
GRANT ROLE PRE_ROLE_INGEST TO USER USR_DLT_PRE_PDE; --INGEST PRE -->  USR_DLT_PRE_PDE
GRANT ROLE PRO_ROLE_INGEST TO USER USR_DLT_PRO_PDE;  --INGEST PRO  -->  USR_DLT_PRO_PDE

GRANT ROLE DEV_ROLE_TRANSFORM TO USER USR_DBT_PDE; --TRANSFORM DEV -->  USR_DBT_PDE
GRANT ROLE PRE_ROLE_TRANSFORM TO USER USR_DBT_PRE_PDE; --TRANSFORM DEV -->  USR_DBT_PRE_PDE
GRANT ROLE PRO_ROLE_TRANSFORM TO USER USR_DBT_PRO_PDE; --TRANSFORM DEV -->  USR_DBT_PRO_PDE